# Generated by Django 5.2.4 on 2025-07-27 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authur', to='book.authur'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='book_genre', to='book.genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
