# Generated by Django 5.2 on 2025-08-10 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_authur_alter_books_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
